# Site settings
title: Chitresh Goel
description: Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chitresh Goel
user_description: 
user_title: Competetive Programmer and Computer Vision Enthusiast
email: goelchitresh13@gmail.com
twitter_username: Chitreshg13
github_username:  cgoxo
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: G-0Y0V4PS82W


exclude: ['package.json', 'src' , 'node_modules']

